[2024-11-15T18:01:39.082+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T18:01:39.107+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Lab9.process_and_sink manual__2024-11-15T18:01:24.145207+00:00 [queued]>
[2024-11-15T18:01:39.118+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Lab9.process_and_sink manual__2024-11-15T18:01:24.145207+00:00 [queued]>
[2024-11-15T18:01:39.119+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-15T18:01:39.138+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): process_and_sink> on 2024-11-15 18:01:24.145207+00:00
[2024-11-15T18:01:39.147+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=875) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T18:01:39.149+0000] {standard_task_runner.py:72} INFO - Started process 879 to run task
[2024-11-15T18:01:39.152+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Lab9', 'process_and_sink', 'manual__2024-11-15T18:01:24.145207+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpku3j24dk']
[2024-11-15T18:01:39.156+0000] {standard_task_runner.py:105} INFO - Job 114: Subtask process_and_sink
[2024-11-15T18:01:39.221+0000] {task_command.py:467} INFO - Running <TaskInstance: Lab9.process_and_sink manual__2024-11-15T18:01:24.145207+00:00 [running]> on host a73688974eca
[2024-11-15T18:01:39.332+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TaiDuongDevOps' AIRFLOW_CTX_DAG_ID='Lab9' AIRFLOW_CTX_TASK_ID='process_and_sink' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T18:01:24.145207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T18:01:24.145207+00:00'
[2024-11-15T18:01:39.333+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T18:01:39.357+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/pymongo/_csot.py:119: UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://www.mongodb.com/docs/languages/python/pymongo-driver/current/faq/#is-pymongo-fork-safe-
  return func(self, *args, **kwargs)

[2024-11-15T18:01:40.450+0000] {logging_mixin.py:190} INFO - Emails, users, and recipients processed and sunk successfully
[2024-11-15T18:01:40.451+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-15T18:01:40.465+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T18:01:40.466+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Lab9, task_id=process_and_sink, run_id=manual__2024-11-15T18:01:24.145207+00:00, execution_date=20241115T180124, start_date=20241115T180139, end_date=20241115T180140
[2024-11-15T18:01:40.527+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-15T18:01:40.553+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T18:01:40.554+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
